language: java
sudo: false
script: mvn ${JACOCO} test
matrix:
 include:
   # Covers Java 7, Open JDK, and code coverage
   - jdk: openjdk7
     env: JACOCO=-Pjacoco
   # Covers Java 8, Oracle JDK
   - jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
git:
  depth: 10
after_success: bash <(curl -s https://codecov.io/bash)
